name: RedSpeed
main: de.redstoneworld.redspeed.RedSpeed
version: 0.0.4
description: A small speed plugin to change the walk- and fly-speed for yourself or and other player.
authors: [RedstoneFuture]
website: https://redstoneworld.de
commands:
  redwalkspeed:
    description: Show or define your walk speed.
    usage: /wspeed <speed or 'default'>
    aliases: [walkspeed, wspeed, ws]
  redflyspeed:
    description: Show or define your fly speed.
    usage: /fspeed <speed or 'default'>
    aliases: [flyspeed, fspeed, fs]